app.factory("Translate", [
  "$state",
  function () {
    return {
      name: "Translate",
      rtl: {
        TEXT_CLIENT_ID:"كود العميل",
        TEXT_SECRET_ID:"الكود السري",
        TEXT_ISSUER:"المصدر",
        TEXT_CONFIGURATION:"التكوين",
        TEXT_E_INVOICES:"الفاتورة الإلكترونيه",
        TEXT_COLLECTION_TYPE: "طريقه التحصيل",
        TEXT_LAST_WEEK: "الاسبوع الماضي",
        TEXT_LAST_MONTH: "الشهر الماضي",
        TEXT_TOTAL_EXPENES: "اجمالي المصروفات",
        TEXT_TOTAL_REVENUE: "اجمالي الايرادات",
        TEXT_CURRENT_BALANCE: "الرصيد",
        TEXT_SAVE_AND_PRINT: "حفظ وطباعه",
        TEXT_COLLECTION_TYPE: "طريقه التحصيل",
        TEXT_LAST_WEEK: "الاسبوع الماضي",
        TEXT_LAST_MONTH: "الشهر الماضي",
        TEXT_TOTAL_EXPENES: "اجمالي المصروفات",
        TEXT_TOTAL_REVENUE: "اجمالي الايرادات",
        TEXT_CURRENT_BALANCE: "الرصيد",
        TEXT_VIEW_REPORTS: "عرض التقارير",
        TEXT_THERE_IS_NOT_REPORT_SELECT: "لا توجد محددات للتقرير",
        TEXT_SELECT_FROM_MENU_REPORTS: "برجاء اختر تقرير من القائمه",
        TEXT_REPORTS: "التقارير",
        MSG_SAME_USER_LOGGED:
          "لقد قمت بالتسجيل من جهاز اخر تسجيل الدخول مره اخري",
        MSG_NOT_ACTIVE_USER: "لقد تم الغاء نشاطك داخل النظام",
        TEXT_LOGIN_AGAIN: "انتهت صلاحية الدخول يرجى تسجيل الدخول مره اخرى",
        MSG_UPDATE_PERMISSION_SUCCESS: "تم تعديل الصلاحيات بنجاح",
        TEXT_PRINT: "طباعه",
        TEXT_EXPORT: "تصدير",
        TEXT_EXPORT_EXCEL: "excel",
        TEXT_EXPORT_PDF: "Pdf",
        TEXT_ADD_SUPPLIER: "اضافة مورد",
        TEXT_ADD_TRANSACTION: "اضافه قيد",
        TEXT_REFERANCE: "رقم المرجع",
        TEXT_ADD_ACCOUNT: "اضافة حساب",
        TEXT_ACCOUNT_CODE: "كود الحساب",
        TEXT_ADD_ITEMS: "اضافه صنف",
        TEXT_BANK_ACCOUNT: "حساب البنوك",
        TEXT_START_BALANCE: "الرصيد الافتتاحي",
        TEXT_NO_DATA: "لايوجد بيانات فى الوقت الحالى",
        AddNewItem: "اضافه صنف",
        //login page
        TEXT_EMAIL_LOGIN: "البريد الالكترونى",
        TEXT_PASSWORD_LOGIN: "الرقم السرى",
        TEXT_PASSWORD_FORGET_LOGIN: "نسيت كلمة المرور",
        TEXT_MAIN_SETTINGS: "الاعدادات الرئيسيه",
        TEXT_SUPPLIER_INV: "فاتوره مشتريات",
        TEXT_UPDATE: "تعديل",
        TEXT_TRANSACTIONS_REPORT: "دفتر الأستاذ",
        TEXT_RESIVE_FROM: "استلمت من",
        TEXT_THE_ACCOUNT: "الحساب",
        TEXT_TO_DATE: "الي تاريخ",
        TEXT_FROM_DATE: "من تاريخ",
        TEXT_TRANSACTION_NUMBER: "رقم القيد",
        TEXT_TRANSACTIONS_NOTES: "قيود اليوميه",
        TEXT_NOTES: "البيان",
        TEXT_ADD_TAX: "اضافة ضريبه",
        TEXT_TAX_NAME: "اسم الضريبه",
        TEXT_TAXES: "الضرايب",
        TEXT_DATE: "التاريخ",
        TEXT_FACTOR_POUND: "الصرف بالجنيه",
        TEXT_FACTOR_DOLAR: "الصرف بالدولار",
        TEXT_ACCOUNT_BALANCE: "رصيد الحساب",
        TEXT_FACTORY: "معامل التحويل",
        TEXT_CURRENCY_NAME: "اسم العمله",
        TEXT_ADD_CURRENCY: "اضافة عمله",
        TEXT_CURRENCIES: "العملات",
        TEXT_CLOSE: "أغلاق",
        TEXT_ADD_COPMANY: "اضافه شركه",
        MSG_YOU_SHOULD_ADD_UNIT: "يجب اضافه وحده لهذا الصنف",
        TEXT_NEXT: "التالي",
        TEXT_SAVE_FINISH: "حفظ وانهاء",
        TEXT_MONEY_TRANSACTIONS: "الحركات المالية",
        TEXT_PAYMONEY: "سند صرف",
        TEXT_CHOOSEBANKORINVENTORY: "اختر حساب خزنه او بتك",
        TEXT_PAY_TO: "مدفوع الى",
        TEXT_COLLECTMONEY: "سند قبض",
        TEXT_AMOUNT: "القيمه",
        TEXT_INV_NUMBER: "رقم الفاتورة",
        TEXT_TO_ACCOUNT: "الي حساب ",
        TEXT_FROM_ACCOUNT: "من حساب ",
        TEXT_REQUIRED: "يجب ادخال هذا الحقل",
        TEXT_CREATE_SAFE: "انشاء خزنه",
        TEXT_EDIT_SAFE: "تعديل خزنه",
        TEXT_storesetting: "اعدادات المخزن",
        TEXT_PRICE_POLICY: "سياسه التسعير",
        Text_COME_FIRST: "القادم اولا",
        Text_COME_MEDIUM: "المتوسط",
        Text_COME_LAST: "القادم اخرا",
        TEXT_AUTOMATICPRICE: "هامش الربح (التسعير التلقائي)",
        TEXT_TYPE: "النوع",
        TEXT_EXTRA_AMOUNT: "قيمه اضافيه",
        TEXT_PERCENT: "نسبه مئويه",
        TEXT_CREATE_BANK: "انشاء بنك",
        TEXT_EDIT_BANK: "تعديل بنك",
        TEXT_SAFE_NAME: "اسم الخزنه",
        TEXT_SAFES: "الخزن",
        TEXT_BANK_NAME: " أسم البنك",
        TEXT_BANK_NAME_ARABIC: "اسم البنك بالعربى",
        TEXT_BANK_NAME_ENGLISH: "اسم البنك بالانجليزيه",

        TEXT_BALANCE: "الرصيد",
        TEXT_ITEM_LIST: "قائمه الاصناف",
        TEXT_ACCOUNT_TYPE: "نوع الحساب",
        TEXT_MAIN_ACCOUNT: "الحساب الرئيسى",
        TEXT_LEVEL: "المستوي",
        TEXT_ACCOUNT_NATURE: "طبيعة الحساب",
        TEXT_ACCOUNT_NAME: "اسم الحساب",
        TEXT_ACCOUNT_NAME_LATINE: "الاسم اللاتيني",
        TEXT_END_ACCOUNTS: "الحسابات الختاميه",
        TEXT_CODE: "الكود",
        TEXT_SEARCH: "بحث",
        TEXT_BANKS: "ألبنوك",
        TEXT_DEALERS: "المتعاملين",
        TEXT_ADD_TAX: "اضافة ضريبه",
        TEXT_TAX_NAME: "اسم الضريبه",
        TEXT_TAXES: "الضرايب",
        TEXT_DATE: "التاريخ",
        TEXT_FACTOR_POUND: "الصرف بالجنيه",
        TEXT_FACTOR_DOLAR: "الصرف بالدولار",
        TEXT_ACCOUNT_BALANCE: "رصيد الحساب",
        TEXT_FACTORY: "معامل التحويل",
        TEXT_CURRENCY_NAME: "اسم العمله",
        TEXT_CURRENCY_NAME_English: "الاسم بالانجليزي",
        TEXT_ADD_CURRENCY: "اضافة عمله",
        TEXT_SYMBOL: "رمز العمله",
        TEXT_DEFAULT: "اجعلها افتراضيه",
        TEXT_DEFAULTSpan: "افتراضيه",
        TEXT_CURRENCIES: "العملات",
        TEXT_CLOSE: "أغلاق",
        TEXT_ADD_COPMANY: "اضافه شركه",
        MSG_YOU_SHOULD_ADD_UNIT: "يجب اضافه وحده لهذا الصنف",
        TEXT_NEXT: "التالي",
        TEXT_MONEY_TRANSACTIONS: "الحركات المالية",
        TEXT_PAYMONEY: "سند صرف",
        TEXT_COLLECTMONEY: "سند قبض",
        TEXT_PAYMONEYS: "سندات صرف",
        TEXT_COLLECTMONEYS: "سندات قبض",
        TEXT_AMOUNT: "القيمه",
        TEXT_INV_NUMBER: "رقم الفاتورة",
        TEXT_TO_ACCOUNT: "الي حساب ",
        TEXT_FROM_ACCOUNT: "من حساب ",
        TEXT_REQUIRED: "يجب ادخال هذا الحقل",
        TEXT_CREATE_SAFE: "انشاء خزنه",
        TEXT_CREATE_BANK: "انشاء بنك",
        TEXT_SAFE_NAME: "اسم الخزنه",
        TEXT_SAFES: "الخزن",
        TEXT_BANK_NAME: "أسم البنك",
        TEXT_BALANCE: "الرصيد",
        TEXT_ITEM_LIST: "قائمه الاصناف",
        TEXT_ACCOUNT_TYPE: "نوع الحساب",
        TEXT_BANKACCOUNTNUMBER: "رقم الحساب",
        TEXT_MAIN_ACCOUNT: "الحساب الرئيسى",
        TEXT_LEVEL: "المستوي",
        TEXT_ACCOUNT_NATURE: "طبيعة الحساب",
        TEXT_ACCOUNT_TYPE_choose: "اختر نوع الحساب",
        TEXT_MAIN_ACCOUNT_choose: " اختر الحساب الرئيسى",
        TEXT_LEVEL_choose: "اختر المستوي",
        TEXT_ACCOUNT_NATURE_choose: "اختر طبيعة الحساب",
        TEXT_END_ACCOUNTS_CHOOSE: "اختر الحساب الختامى",
        TEXT_ACCOUNT_NAME: "اسم الحساب",
        TEXT_CODE: "الكود",
        TEXT_SEARCH: "بحث",
        TEXT_BANKS: "ألبنوك",
        TEXT_DEALERS: "المتعاملين",
        TEXT_DASHBOARD: "الصفحة الرئيسية",
        TEXT_USERS: "المستخدمين",
        TEXT_Roles: "الصلاحيات",
        TEXT_LOGOUT: "تسجل خروج",
        TEXT_SIGNIN: "تسجل دخول",
        TEXT_USER_ACCOUNT: "الملف الشخصى",
        TEXT_CREATE_USER: "إنشاء مستخدم",
        TEXT_USER_CODE: "كود المستخدم",
        TEXT_USER_NAME: "أسم المستخدم",
        TEXT_USER_CREATION_DATE: "تاريخ الأنشاء",
        TEXT_FULL_NAME: "الأسم الكامل",
        TEXT_PASSWORD: "كلمة المرور",
        TEXT_Dark_Mode: "الوضع الليلى",
        TEXT_SYSTEM_INFO: "معلومات عن النظام",
        TEXT_PERSONAL_INFORMATION: "المعلومات الشخصيه",
        TEXT_USERNAME: "أسم المستخدم",
        TEXT_CONFIRM_PASSWORD: "تاكيد كلمة المرور",
        TEXT_AGENT: "مندوب",
        TEXT_EMPLOYEE: "موظف",
        TEXT_ADDRESS: "العنوان",
        TEXT_NATIONALITY: "الجنسية",
        TEXT_ADD_USER: "أضافة مستخدم",
        TEXT_LOGOUT: "تسجيل الخروج",
        TEXT_PLACEHOLDER_SEARCH: "بحث ...",
        TEXT_EDIT: "تعديل",
        TEXT_EDIT_PERMISSIONS: "تعديل الصلاحيات",
        TEXT_REMOVE: "حذف",
        TEXT_ADD: "أضافة",
        TEXT_CANCEL: "إلغاء",
        TEXT_SAVE: "حفظ",
        TEXT_NEXT: "التالي",
        TEXT_OPTIONS: "الخيارات",
        TEXT_CHARTOFACCOUNT: "دليل الحسابات",
        TEXT_ACCOUNTS: " الحسابات",
        TEXT_View: "عرض",
        TEXT_Create: "إنشاء",
        TEXT_Delete: "حذف",
        TEXT_Print: "طباعه",
        TEXT_PREVIEW_ALL: "معاينة الكل",
        TEXT_Edit: "تعديل",
        TEXT_PERMISSION: "الصلاحية",

        TEXT_USERS_AND_PERMISSIONS: "المستخدمين و الآذونات",
        TEXT_GENERAL_LEDGER: "دفتر الاستاذ العام",
        TEXT_SALE_AND_PURCHASE: "البيع و الشراء",
        TEXT_INVENTORY: "المخزون",
        TEXT_HR: "الموارد البشرية",

        //reset password
        Text_update_password: "تعديل كلمة المرور",
        Text_message: "شكرا لتاكيدك الايميل ,فلنعدل كلمة مرورك ",
        TEXT_EMAIL_REQUIRED: "البريد الالكترونى مطلوب",
        TEXT_PASSWORD: "كلمة المرور",
        TEXT_PASSWORD_REQUIRED: "كلمة المرور مطلوبة",
        TEXT_CONFIRM_PASSWORD: "تاكيد كلمة المرور",
        TEXT_CONFIRM_PASSWORD_REQUIRED: "تاكيد كلمة المرور مطلوبه ",
        MSG_INVALID_EMAIL: "الايميل غير صحيح",
        TEXT_RESET_PASSWORD: "اعادة تعيين كلمة المرور",
        TEXT_MESSAGE_INSTRUCT:
          "ان كنت قد نسيت كلمة مرورك ,فسنرسل لك ارشادات عبر البريد الكتروني لاعادة تعيين كلمة مرورك",
        TEXT_RESET_LINK: "ارسل رابط اعادة التعيين ",
        TEXT_RETURN_LOGIN: "عد لصفحة تسجيل الدخول",
        TEXT_ENTER_EMAIL: "ادخل بريدك الاكتروني",
        TEXT_PASS_CONFPASS_NOT_MATCH:
          "كلمة المرور وتاكيد كلمة المرور غير منطبقين",
        TEXT_ENTER_PASSWORD: "ادخل كلمة المرور",
        TEXT_CONFIRM_ENTER_PASSWORD: "ادخل تاكيد كلمة المرور",
        TEXT_LATER: "لاحقا",
        TEXT_BASIC_INFO:
          "المعلومات الاساسيه ,مثل اسمك وعنوانك ورقم الهاتف التى تستخدمها داخل النظام.",
        TEXT_BASICS: "المعلومات الاساسيه",
        /* permissions */
        TEXT_Admin: "",
        TEXT_User: "المستخدمين",
        TEXT_CHART_OF_ACCOUNT: "دليل الحسابات",
        TEXT_COST_CENTERS: "مراكز التكلفة",
        TEXT_ASSETS: "الأصول",
        TEXT_SUPLIERS: "الموردين",
        TEXT_CUSTOMERS: "الزبائن",
        TEXT_BANKS: "اسماء البنوك",
        TEXT_CASES: "خزن",
        TEXT_TRANSACTIONS: "معاملات",
        TEXT_Role: "الصلاحيات",
        TEXT_Users: "المستخدمين",
        TEXT_product: "المنتجات",
        TEXT_Category: "التصنيفات",
        TEXT_Store: "المخازن",
        TEXT_Currency: "العملات",
        TEXT_Inventory: "الخزن",
        TEXT_SupplierInvoice: "فواتير شراء",
        TEXT_CustomerInvoice: "فواتير بيع",
        TEXT_Accountant: "الحسابات",
        TEXT_Customer: "العملاء",
        TEXT_Supplier: "الموردين",
        TEXT_Branch: "الفروع",
        TEXT_Company: "الشركه",
        TEXT_Transaction: "القيود",
        TEXT_PayMoney: "السندات",
        TEXT_INVOICES: "الفواتير",
        TEXT_Bank: "البنوك",
        TEXT_SalesInvoicesReport: "تقرير فواتير المبيعات",
        TEXT_CustomersInvoicesWithFilterReport: "تقرير فواتير العملاء ",
        TEXT_SalesInvoiceReport: "تقرير فاتوره مبيعات",
        TEXT_InvoicesEarningsReport: "تقرير ارباح الفواتير",
        TEXT_ProductsEarningsReport: "تقرير ارباح الاصناف",
        TEXT_SupplierInvoicesReport: "تقرير فواتير المشتريات",
        TEXT_MostActiveSuppliersReport: "تقرير الموردين الاكثر حركه",
        TEXT_ProductsMovementsReport: "تقرير حركة الاصناف",
        TEXT_ProductMovementReport: "تقرير حركه صنف",
        TEXT_ProductsReport: "تقرير الاصناف",
        TEXT_DemandLimitReport: "تقرير حد الطلب",
        TEXT_ProductExpirationReport: "تقرير الصلاحيه",
        TEXT_StoreMovementReport: "تقرير حركه مخزن",
        TEXT_KsaInvoice: "الفاتوره السعوديه",
        TEXT_LedgerReport: "تقرير دفتر الاستاذ",
        TEXT_CustomerStatementReport: "تقرير كشف حساب عميل",
        TEXT_CustomersReport: "تقرير العملاء    ",
        TEXT_MostActiveCustomersReport: "تقرير العملاء الاكثر حركه",
        TEXT_CustomerMovementAsInvoicesReport:
          "تقرير حركه العميل بناء علي الفواتير ",
        TEXT_CustomerMovementAsPayMoneyReport:
          "تقرير حركة العميل بناء علي السندات",
        TEXT_SupplierStatemntReport: "تقرير كشف حساب مورد",
        TEXT_supplierReport: "تقرير المورد",
        TEXT_SupplierMovementAsInvoicesReport:
          "تقرير حركه المورد بناء علي الفواتير  ",
        TEXT_SupplierMovementsAsPayMoney: "تقرير حركه المورد بناء على السندات",
        TEXT_Backup: "النسخه الاحتياطيه",
        TEXT_RETURNS: "المرتجعات",
        TEXT_FREE_RETURNS: "المرتجع الحر",
        TEXT_BRANSHES: "الافرع",
        TEXT_COMISSIONS: "العلاوات",
        TEXT_DISCOUNTS: "الخصومات",

        TEXT_WAREHOUSE: "المستودع",
        TEXT_ITEMS: "المنتجات",
        TEXT_BARCODES: "الباركود",
        TEXT_UNITES: "الوحدات",

        TEXT_EMPLOYEE_FILES: "ملفات الموظفين",
        TEXT_PAYROLL: "كشف رواتب",
        TEXT_PAYSLIP: "قسائم دفع",
        TEXT_BENEFITS: "الاستحقاقات",
        TEXT_DEDUCTIONS: "الاستقطاعات",
        TEXT_HOLIDAYS: "الاجازات",

        TEXT_ITEMS: "المنتجات",
        TEXT_ITEM_CODE: "كود المنتج",
        TEXT_ITEM_NAME: "اسم المنتج",
        TEXT_ITEM_CREATION_DATE: "تاريخ انشاء المنتج",
        TEXT_CREATE_ITEM: "انشاء منتج",

        TEXT_CREATE_ITEM: "انشاء منتج",
        TEXT_ITEM_NAME: "اسم المنتج",
        TEXT_ITEM_DESCRIPTION: "وصف المنتج",
        TEXT_CHOOSE_CATEGORIES: "أختار الفئة الخاصة بالمنتج",

        // Messages
        MSG_NO_RESULT: "لا يوجد اى نتائح حالياً",
        MSG_REQUIRED: "مطلوب * من فضلك قم بملاء هذه الخانة اولاً",

        MSG_UNMATCHED: "كلمة المرور غير متطابقة",
        MSG_WENT_WRONG: "!حدث خطاء غير معلوم",
        MSG_Login_Failed: "أسم المستخدم او كلمة المرور غير صحيح :/",
        MSG_DUPLICATE_NAME: "هذا الاسم مستخدم بالفعل",
        MSG_LOGIN_SUCCESS: "تم الدخول بنجاح",
        MSG_ADDEDSUCCESSFULLY: "تم الاضافه بنجاح",
        MSG_DELETED_SUCCESSFULLY: "تم الحذف بنجاح",
        MSG_UPDATEDSUCCESSFULLY: "تم التعديل بنجاح",
        MSG_COMPANYNAMEEXIST: "اسم الشركه موجود مسبقا",
        MSG_BRANCHNAMEEXIST: "اسم الفرع موجود مسبقا",
        MSG_SUPPLIEREXIST: "اسم المورد موجود مسبقا",
        MSG_CUSTOMEREXIST: "اسم العميل موجود مسبقا",
        MSG_NOACCESS: "ليس لديك صلاحيه",
        TEXT_NOT_ADDED: "لم يتم إضافة بعد ",
        TEXT_UPDATE_PROFILE: "تعديل الملف الشخصى",
        MSg_USEREXIST: "اسم المستخدم او البريد الالكترونى موجود مسبقا",
        MSG_DEFAULTCURRENCYEXIST:
          "يوجد عمله افتراضيه بالفعل قم بالغاؤها ومحاولة اختيار هذه العمله كأفتراضيه",
        MSG_TAXEXIST: "الضريبه موجوده مسبقا",
        MSG_STORE_EXIST: "المخزن موجود مسبقا",
        MSG_CATEGORY_EXIST: "التصنيف موجود مسبقا",
        MSG_UNIT_EXIST: "الوحده موجوده مسبقا",
        MSG_SUCCESS: "نجاح",
        MSG_OLD_PASSWORD_INCORRECT: "كلمة السر الحاليه غير صحيحه",
        MSG_another_user_already_loged: " المستخدم قام بالدخول مسبقا",
        MSG_PRODUCT_EXIST: "المنتج موجود مسبقا",
        MSG_STORE_NOT_EXIST: "المخزن غير موجود",
        MSG_CATEGORY_NOT_EXIST: "المجموعه غير موجوده",
        MSG_PRODUCT_CODE_EXIST: "كود الصنف موجود مسبقا",
        // settings
        TEXT_BACK: "رجوع",
        TEXT_SETTINGS: "الاعدادات",
        ADD: "اضافه",
        CANCEL: "الغاء",
        CHOOSE: "اختر",
        UPDATE: "تعديل",
        CONFIRM: "تاكيد",
        CONFIRMMESSAGE: "هل انت متاكد",
        MSG_DEFAULTCURRENCYADDED: "تم تعيين العمله الافتراضيه بنجاح",
        TEXT_CHOOSEDEFAULTCURRENCY: "اختيار العمله الافتراضيه",
        //user

        TEXT_CREATE_USER: "اضافه مستخدم",
        TEXT_EDITUSER: "تعديل مستخدم",
        TEXT_USERS: "المستخدمين",
        USERNAME: "اسم المستخدم",
        ROLE: "الصلاحيه",
        STATE: "الحاله",
        Password: "الرقم السري",
        ISNOTACTIVE: "غير مفعل",
        ISACTIVE: "مفعل",
        TEXT_ROLE_REQUIRED: "اسم الصلاحيه مطلوب",
        TEXT_EMAIL_REQUIRED: "البريد الالكترونى مطلوب",
        TEXT_PASSWORD_REQUIRED: "الرقم السرى مطلوب",
        MSG_ROLE_EXIST: "الصلاحيه موجوده بالفعل",
        MSG_ACCOUNT_EXIST: "الحساب موجود مسبقا",
        //Text_addcompany
        Text_addcompany: "اضافه شركه",
        Text_companyName: "اسم الشركه",
        Text_companyactivity: "نشاط الشركه",
        Text_companyRegNo: "رقم التسجيل",
        Text_companyTaxcard: "البطاقه الضريبيه",
        Text_companyAddress: "العنوان",
        Text_phone: "التليفون",
        Text_mobilephone: "التليفون المحمول",
        Text_Email: "الايميل",
        Text_website: "الموقع الالكتروني",
        Text_logo: "الشعار",
        Text_curreny: "العمله",
        TEXT_COUNTRY: "الدوله",
        Text_branchName: "اسم الفرع",
        TEXT_BRANCHREQUIRED: "اسم الفرع مطلوب  ",

        Text_addbranch: "اضافه فرع",
        TEXT_EDITCOMPANYINFO: "تعديل بيانات الشركه",
        TEXT_BRANCHLIST: "قائمه الفروع",
        TEXT_COMPANYSETTING: "اعدادات الشركه",
        TEXT_BRANCHSETTING: "اعدادات الفروع",
        Text_COMPANYINFO: "بيانات الشركه",
        TEXT_EDITBRANCHINFO: "تعدبل بيانات الفرع",
        TEXT_UPDATETAX: "تعديل الضريبه",
        TEXT_UPDATECURRENCY: "تعديل العمله",
        //PRODUCT
        TEXT_ADDPRODUCT: "اضافه صنف",
        maininformation: "المعلومات الرئيسيه",
        TEXT_PRODUCTCODE: "كود الصنف",
        TEXT_PRODUCTNAME: "اسم الصنف",
        category: "المجموعه",
        store: "المخزن",
        TEXT_CATEGORY: "المجموعه",
        addProduct: "اضافة منتج ",
        store: "المخزن",
        demandLimit: "حد الطلب",
        addStore: "اضافة مخزن",
        addCategory: "اضافة مجموعه",
        storeRequired: "المخزن مطلوب",
        description: "الوصف",
        descriptionRequired: "الوصف مطلوب",
        categoryName: "اسم المجموعة",
        storeName: "اسم المخزن",
        code: "الكود",
        codeRequired: "الكود مطلوب",
        productName: "اسم المنتج",
        nameRequired: "الاسم مطلوب",
        productBarCode: "الباركود",
        units: "الوحدات",
        barCodeRequired: "الباركود مطلوب",
        price: "السعر",
        priceRequired: "السعر مطلوب",
        categoryadd: "اضافة مجموعه",
        categoryRequired: "المجموعة مطلوبة",
        sellerPrice: "سعر البيع",
        sellerPriceRequired: "سعر البيع مطلوب",
        purchesePrice: "سعر الشراء",
        purchesePriceRequired: "سعر الشراء مطلوب",
        tax: "الضريبة",
        taxRequired: "الضريبة مطلوبة",
        stock: "المخزون",
        stockRequired: "المخزون مطلوب",
        orderLimit: "حد الطلب",
        orderLimitRequired: "حد الطلب مطلوب",
        unitName: "اسم الوحدة",
        unitNameRequired: "اسم الوحدة مطلوب",
        sellingprice: "سعر البيع ",
        purchasingPric: "سعر الشراء",
        defaultSelling: "افتراضي بيع",
        defaultPurchasing: "افتراضي شراء",
        unitPriceRequired: "سعر الوحدة مطلوب",
        isExpiration: "له صلاحية",
        Expiration: "الصلاحيه",
        productionDate: "تاريخ الانتاج",
        productionDateRequired: "تاريخ الانتاج مطلوب ",
        expirationDate: "تاريخ الانتهاء",
        expirationDateRequired: "تاريخ الانتهاء مطلوب ",
        width: "العرض",
        widthRequired: "العرض مطلوب",
        height: "الطول",
        heightRequired: "الطول مطلوب",
        elevation: "الارتفاع",
        elevationRequired: "الارتفاع مطلوب",
        size: "الحجم",
        sizeRequired: "الحجم مطلوب",
        weight: "الوزن القائم",
        weightRequired: "مطلوب",
        netWeight: "الوزن الصافي",
        netWeightRequired: "مطلوب",
        selectStore: "اختر المخزن ",
        selectCategory: "اخترالتصنيف",
        units: "الوحدات",
        dimensions: "الابعاد",
        add: "اضافة",
        AddNewUnit: "اضافة وحده جديده",
        currentBalance: "الرصيد الحالي",
        startbakance: "الرصيد الافتتاحي",
        balanceUnit: "وحدة الرصيد الافتتاحي",
        balanceCost: "تكلفة الرصيد",
        completAccount: "الحساب المكمل",
        choseUnit: "---اختار وحدة---",
        choseAccount: "----اختار الحساب----",
        defaultSell: "افتراضي بيع",
        defaultPerchase: "افتراضي شراء",
        storeaccount: "المخزون",
        storeaccount: "رصيد المخزون",
        editproduct: "تعديل صنف",
        storeaccountbalance: "حساب المخزون",
        TEXT_QUANTITY: "الكميه",
        TEXT_TOTALUNITPRICE: "اجمالي الوحدات",
        TEXT_TOTAL: "الاجمالي",

        // category

        // dashboard
        DASHBOARD: "لوحه التحكم",
        //role
        Text_Roles: "الصلاحيات",
        Text_AddRole: "اضافة صلاحيه",
        Text_RoleName: "اسم الصلاحيه",
        Text_RoleRequired: "اسم الصلاحيه مطلوب",
        Text_deleteRole: "حذف الصلاحيه",
        Text_ManagePermission: "تعديل الصلاحيات",
        Text_AddAndDeletePermission: "اضافة /حذف صلاحيه",
        TEXT_SELECTALL: "اختيار او حذف جميع الصلاحيات",
        Text_Module: "اسم المسار",
        Text_PermissionModule: "الصلاحيه",
        Text_ConfirmdeleteRole: "هل انت متأكد من حذف الصلاحيه",
        //customers
        TEXT_ADDCUSTOMER: "اضافة عميل",
        TEXT_CUSTOMERS: "العملاء",
        TEXT_EXIST: "يوجد لديك عدد",
        TEXT_Customer: "عميل",
        TEXT_CustomerName: "اسم العميل",
        Text_Balance: "الرصيد",
        Text_Address: "العنوان",
        TEXT_customerRequired: "اسم العميل مطلوب",
        TEXT_AddressRequired: "العنوان مطلوب",
        TEXT_PhoneRequired: "رقم الموبايل مطلوب",
        TEXT_FAX: "الفاكس",
        TEXT_DISCOUNT: "الخصم",
        TEXT_DEBIT: "مدين",
        TEXT_CREDIT: "دائن",
        TEXT_HomeMobile: "التليفون الارضى",
        TEXT_UPDATECUSTOMER: "تعديل عميل",
        TEXT_CUSTOMERANDSUPPLIER: "عميل و مورد",
        //suppliers
        TEXT_ADDSUPPLIER: "اضافة مورد",
        TEXT_SUPPLIERS: "الموردين",
        TEXT_EXIST: "يوجد لديك عدد",
        TEXT_Supplier: "مورد",
        TEXT_SupplierName: "اسم المورد",
        Text_Balance: "الرصيد",
        Text_Address: "العنوان",
        TEXT_supplierRequired: "اسم المورد مطلوب",
        TEXT_AddressRequired: "العنوان مطلوب",
        TEXT_PhoneRequired: "رقم الموبايل مطلوب",
        TEXT_FAX: "الفاكس",
        TEXT_DISCOUNT: "الخصم",
        TEXT_DEBIT: "مدين",
        TEXT_CREDIT: "دائن",
        TEXT_HomeMobile: "التليفون الارضى",
        TEXT_UPDATESUPPLIER: "تعديل مورد",
        TEXT_SUPPLIERANDCUSTOMER: "مورد و عميل",
        //bank accounts
        TEXT_BANKACCOUNTS: "حسابات البنوك",
        TEXT_BANK_ACCOUNTS: "حساب بنكى",
        TEXT_ACCOUNT_TYPE: "نوع الحساب",
        TEXT_BANKACCOUNTNUMBER: "رقم الحساب",
        TEXT_BANKACCOUNTNAME: "اسم صاحب الحساب",
        TEXT_BANKACCOUNTNAMEREQUIRED: "اسم صاحب الحساب مطلوب",
        TEXT_BANKACCOUNTNUMBERREQUIRED: "رقم الحساب مطلوب",
        TEXT_BANKREQUIRD: "اسم البنك مطلوب",
        TEXT_UPDATEBANKACCOUNT: "تعديل حساب بنكى",
        TEXT_FACTOR: "سعر الصرف بالنسبه للعمله الافتراضيه",
        // customer Invoice
        TEXT_CUSTOMER_INVOICE: "فواتير بيع",
        TEXT_ADDCUSTOMERINVOICE: "اضافة فاتورة بيع",
        TEXT_INVOICENUMBER: "رقم الفاتوره",
        TEXT_DESCRIPTION: "الوصف",
        TEXT_CUSTOMERINVOICEDATE: "تاريخ الفاتوره",
        TEXT_PAYMENTTYPE: "طريقة الدفع",
        TEXT_ADDPAYMENTTYPE: "اضافة طريقة دفع",
        TEXT_PAYMENTNAME: "طريقة الدفع",
        MSG_PAYMENTEXIST: "طريقة الدفع موجوده مسبقا",
        TEXT_INVOICEDETAILS: "تفاصيل الفاتوره",
        TEXT_QUANTITY: "الكميه",
        TEXT_UNIT: "الوحده",
        TEXT_TOTALUNITPRICE: "السعر الكلى للوحده",
        TEXT_TAX: "الضريبه",
        TEXT_TOTAL: "السعر الكلى",
        TEXT_CURRENCY: "العمله",
        TEXT_ADDNEW: "اضافة جديد",
        TEXT_ADD_TRANSACTION: "اضافة قيد ",
        //invoice

        TEXT_INVOICES: "الفواتير",
        TEXT_SUPLIERSINVOICE: "فاتوره شراء",
        TEXT_ADDSUPPLIERINVOICE: "اضافه فاتوره شراء",
        Text_ADDINVOICE: "اضافه فاتوره",
        TEXT_SUPLIERSINVOICES: "فواتير شراء",
        //bank accounts
        TEXT_BANKACCOUNTS: "حسابات البنوك",
        TEXT_BANK_ACCOUNTS: "حساب بنكى",
        TEXT_ACCOUNT_TYPE: "نوع الحساب",
        TEXT_BANKACCOUNTNUMBER: "رقم الحساب",
        TEXT_BANKACCOUNTNAME: "اسم صاحب الحساب",
        TEXT_BANKACCOUNTNAMEREQUIRED: "اسم صاحب الحساب مطلوب",
        TEXT_BANKACCOUNTNUMBERREQUIRED: "رقم الحساب مطلوب",
        TEXT_BANKREQUIRD: "اسم البنك مطلوب",

        //ui-select placeholders
        TEXT_CHOOSEROLE: "اختر الصلاحيه",
        TEXT_CHOOSEBANK: "اختر اسم البنك",
        TEXT_CHOOSEBANKACCOUNTTYPE: "اختر نوع الحساب",
        TEXT_CHOOSEACCOUNT: "اختر الحساب",
        TEXT_CHOOSECURRENCY: "اختر العمله",
        TEXT_CHOOSESUPPLIER: "اختر المورد",
        TEXT_CHOOSECUSTOMER: "اختر العميل",
        TEXT_CHOOSEPATTYPE: "اختر طريقة الدفع",
        TEXT_CHOOSEBRANCH: "اختر الفرع",
        //superAdmin logs
        TEXT_SUPERADMIN_LOG_MESSAGE: "الحدث",
        TEXT_SUPERADMIN_LOG_level: "المستوى",
        TEXT_SUPERADMIN_LOG_TIME: "الوقت",
        TEXT_SUPERADMIN_USER_LOG: "الجهاز المستخدم",
        // customer Invoice
        TEXT_ADDCUSTOMERINVOICE: "اضافة فاتورة بيع",
        TEXT_INVOICENUMBER: "رقم الفاتوره",
        TEXT_DESCRIPTION: "الوصف",
        TEXT_CUSTOMERINVOICEDATE: "تاريخ الفاتوره",
        TEXT_PAYMENTTYPE: "طريقة الدفع",
        TEXT_ADDPAYMENTTYPE: "اضافة طريقة دفع",
        TEXT_PAYMENTNAME: "طريقة الدفع",
        MSG_PAYMENTEXIST: "طريقة الدفع موجوده مسبقا",
        TEXT_INVOICEDETAILS: "تفاصيل الفاتوره",
        TEXT_QUANTITY: "الكميه",
        TEXT_INVOICEMADEBY: "المسئول",
        TEXT_UNIT: "الوحده",
        TEXT_TOTALUNITPRICE: "السعر الكلى للوحده",
        TEXT_TAX: "الضريبه",
        TEXT_TOTAL: "السعر الكلى",
        TEXT_CURRENCY: "العمله",
        TEXT_ADDNEW: "اضافة جديد",
        TEXT_CUSTOMERINVOICE: "فواتير بيع",
        TEXT_PAIED: "المدفوع",
        TEXT_SPEND_PRICE: "سعر الصرف",
        AVAILABLE_STOCK: "الكميه المتاحه",
        //logs
        TEXT_LOGS: "السجل",
        Text_ACTION_LOG: "الحدث",
        Text_USER_LOG: "المستخدم المسئول",
        Text_DESCRIPTION_LOG: "الوصف",
        TEXT_DATE_LOG: "تاريخ العمليه",
        //store relocation
        TEXT_STORE_RELOCATION: "حركات المخازن",
        TEXT_ADD_PRODUCT_RELOCATE: "اضافة منتج للترحيل",
        TEXT_ADD_STORE_RELOCATE: "اضافة حركة مخزن",
        TEXT_STORE_FROM: "من مخزن",
        TEXT_STORE_TO: "الى مخزن",
        MSG_RELOCATE_SUCCESSFULLY: "تم الترحيل بنجاح",
        TEXT_DESCRIPTION: "الوصف",

        TEXT_PRODUCT_RELOCATE: "اسم المنتج",
        TEXT_QUANTITY_RELOCATE: "الكميه المراد ترحيلها",
        TEXT_AMOUNT_RELOCATE: "المتبقي",
        TEXT_STOCK_RELOCATE: "المخزون",

        //categories
        TEXT_CATEGORIES: "التصنيفات",
        TEXT_CATEGORY_NAME: "اسم التصنيف",
        Text_Category_REQUIRED: "اسم التصنيف مطلوب",
        TEXT_UPDATE_CATEGORY: "تعديل تصنيف",

        // manage stores
        TEXT_STORES: "المخازن",
        TEXT_STORE_NAME: "اسم المخزن",
        Text_Category_REQUIRED: "اسم المخزن مطلوب",
        TEXT_UPDATE_STORE: "تعديل مخزن",
        //manage units
        TEXT_UNITS: "الوحدات",
        TEXT_UNIT_NAME: "اسم الوحده",
        Text_UNIT_REQUIRED: "اسم الوحده مطلوب",
        TEXT_UPDATE_UNIT: "تعديل وحده",
        TEXT_ADD_UNIT: "اضافه وحده",
        //change password
        TEXT_CURRENT_PASSWORD: "كلمة السر الحاليه",
        TEXT_NEW_PASSWORD: "كلمة السر الجديده",
        TEXT_CONFIRM_NEW_PASSWORD: "تأكيد كلمة السر الجديده",
        Text_CHANGE_password: "تأكيد تغيير كلمة السر",
        TEXT_CHANGE_TITLE_PASSWORD: "تغيير كلمة السر",
        TEXT_PASSWORD_CURRENT_REQUIRED: "كلمة السر الحاليه مطلوبه",
        TEXT_PASSWORD_NEW_REQUIRED: "كلمة السر الجديده مطلوبه",
        TEXT_CONFIRM__NEW_PASSWORD_REQUIRED: "تأكيد كلمة السر مطلوب",
        TEXT_INTERVAL: "الفتره الزمنيه لحذف السجل",
        TEXT_Daily: "يوميا",
        TEXT_Weekly: "اسبوعيا",
        TEXT_Monthly: "شهريا",
        TEXT_Yearly: "سنويا",
        TEXT_BACKUP: "النسخه الاحتياطيه",
        TEXT_BACKUP_DB: "النسخه الاحتياطيه لقواعد البيانات",
        TEXT_TAKE_BACKUP: "اخذ نسخه احتياطيه",
        MSG_BACKUP_SUCCESS: "تم اخذ نسخه احتياطيه بنجاح",
        TEXT_BACUP_FILE: "اسم الملف",
        TEXT_CREATION_AT: "التوقيت",
        TEXT_RESTORE: "استعاده النسخه الاحتياطيه",
        MSG_RESTORE_SUCCESS: "تم استعاده النسخه الاحتياطيه بنجاح",
        TEXT_COST: "مركز التكلفه",
      },
      ltr: {
        TEXT_CLIENT_ID:"Client id",
        TEXT_SECRET_ID:"Secret Id",
        TEXT_ISSUER:"Issuer",
        TEXT_CONFIGURATION:"configuration",
        TEXT_E_INVOICES:"E-invoice",
        TEXT_LAST_WEEK: "Last Week",
        TEXT_LAST_MONTH: "Last month",
        TEXT_TOTAL_EXPENES: "Total Expenses",
        TEXT_TOTAL_REVENUE: "Total Revenue",
        TEXT_CURRENT_BALANCE: "Total Balance",
        TEXT_VIEW_REPORTS: "View reports",
        TEXT_THERE_IS_NOT_REPORT_SELECT: "There are no report settings",
        TEXT_SELECT_FROM_MENU_REPORTS: "Please choose a report from the list",
        TEXT_REPORTS: "Reports",
        TEXT_LOGIN_AGAIN: "session expired log in again",
        MSG_SAME_USER_LOGGED:
          "You are logged in from another device log in again",
        MSG_NOT_ACTIVE_USER: "you are not active in system",
        TEXT_ADD_SUPPLIER: " add supplier",
        TEXT_USER_ACCOUNT: "Account Setting",
        TEXT_Dark_Mode: "Dark Mode",
        TEXT_SYSTEM_INFO: "System Info",
        TEXT_PERSONAL_INFORMATION: "Personal Information",
        TEXT_BASIC_INFO:
          "Basic info, like your name and address, that you use on System.",
        TEXT_BASICS: "BASICS",
        TEXT_NOT_ADDED: "Not add yet",
        TEXT_UPDATE_PROFILE: "Update Profile",
        TEXT_LOGOUT: "Log Out",
        TEXT_START_BALANCE: "opening balance",
        TEXT_BANK_ACCOUNT: "Bank account",
        TEXT_SUPPLIER_INV: "purchase invoice",
        TEXT_ADD_ITEMS: "add items",
        TEXT_ADD_TRANSACTION: "Add transaction",
        TEXT_REFERANCE: "Referance",
        TEXT_ADD_ACCOUNT: "Add account",
        TEXT_ACCOUNT_CODE: "Account Code",
        TEXT_ACCOUNTS: " Accounts",
        TEXT_CHARTOFACCOUNT: "Chart Of Accounts",
        TEXT_TRANSACTIONS_REPORT: "Master Book",
        TEXT_BANK_ACCOUNT: "Bank Accounts",
        TEXT_Roles: "Roles",
        TEXT_NO_DATA: "No data found",
        MSG_SUCCESS: "success",
        //SupllierInvoice
        TEXT_SUPLIERSINVOICES: "Purchasing Invoices",
        Text_ADMINSTRATOR: "Administrator",
        Text_BRANCH: "Branch",
        Text_PAID: "Paid",
        AddNewItem: "Add Item",

        Text_: "",
        Text_: "",
        Text_: "",
        Text_: "",
        Text_: "",
        Text_: "",
        Text_: "",
        Text_: "",
        Text_: "",
        Text_: "",
        Text_: "",
        Text_: "",
        Text_: "",
        Text_: "",
        Text_: "",
        Text_: "",
        TEXT_ACCOUNT_TYPE: "Account Type",
        TEXT_MAIN_ACCOUNT: "Main Account",
        TEXT_LEVEL: "Level",
        TEXT_ACCOUNT_NATURE: "Account Nature",
        TEXT_ACCOUNT_NAME: "Account Name",
        TEXT_ACCOUNT_NAME_LATINE: "Account Name Latinian",
        TEXT_REPORT_TYPE: "Report Type",
        TEXT_MAIN_ACCOUNT_CHOOSE: " choose main account",
        TEXT_LEVEL_choose: " choose level",
        TEXT_ACCOUNT_NATURE_choose: "choose account nature",
        TEXT_ACCOUNT_NAME_LATINE: "Account Name Latinian",
        TEXT_REPORT_TYPE_choose: "chhose report type",
        //login page
        TEXT_PASSWORD_LOGIN: "Password",
        TEXT_PASSWORD_FORGET_LOGIN: "Forget password",
        TEXT_MAIN_SETTINGS: "Main Settings",
        TEXT_User: "Users",
        TEXT_View: "view",
        TEXT_Create: "create",
        TEXT_Delete: "delete",
        TEXT_Print: "print",
        TEXT_PREVIEW_ALL: "PreviewAll",
        TEXT_Edit: "edit",
        TEXT_RESIVE_FROM: "Resived from",
        TEXT_THE_ACCOUNT: "The account",
        TEXT_TO_DATE: "To date",
        TEXT_FROM_DATE: "From date",
        TEXT_TRANSACTION_NUMBER: "Transaction num",
        TEXT_TRANSACTIONS_NOTES: "Transactions",
        TEXT_NOTES: "Notes",
        TEXT_ADD_TAX: "Add tax",
        TEXT_TAX_NAME: "Tax Name",
        TEXT_TAXES: "Taxes",
        TEXT_DATE: "Date",
        TEXT_FACTOR_POUND: "Factor to pound",
        TEXT_FACTOR_DOLAR: "Factor to dolar",
        TEXT_ACCOUNT_BALANCE: "Account balance",
        TEXT_FACTORY: "Factory",
        TEXT_CURRENCY_NAME: "Currency name",
        TEXT_storesetting: "Store Settings",
        TEXT_PRICE_POLICY: "Price Policy",
        TEXT_AUTOMATICPRICE: "Automatic Price",
        Text_COME_FIRST: "Come First",
        Text_COME_MEDIUM: "Medium",
        Text_COME_LAST: "Come Last",
        TEXT_TYPE: "Type",
        TEXT_EXTRA_AMOUNT: "Extra Amount",
        TEXT_PERCENT: "Percent",
        TEXT_ADD_CURRENCY: "Add currency",
        TEXT_CURRENCIES: "Currencies",
        TEXT_CLOSE: "Close",
        TEXT_ADD_COPMANY: "Add company",
        MSG_YOU_SHOULD_ADD_UNIT: "You should add one unit to this item",
        MSG_ACCOUNT_EXIST: "account exist",
        MSG_UPDATE_PERMISSION_SUCCESS: "Permission updated successfully",
        TEXT_NEXT: "Next",
        TEXT_SAVE_FINISH: "SaveAndFinish",

        TEXT_MONEY_TRANSACTIONS: "Money transactions",
        TEXT_PAYMONEY: "Pay money",
        TEXT_PAYMONEYS: "Pay moneys",

        TEXT_CHOOSEBANKORINVENTORY: "Bank or Inventory",
        TEXT_COLLECTMONEY: "Collect money",
        TEXT_COLLECTMONEYS: "Collect moneys",

        TEXT_AMOUNT: "amount",
        TEXT_INV_NUMBER: "Invoice Num",
        TEXT_TO_ACCOUNT: "To account",
        TEXT_FROM_ACCOUNT: "From account",
        TEXT_REQUIRED: "this field is required",
        TEXT_CREATE_SAFE: "add safe",
        TEXT_CREATE_BANK: "add bank",
        TEXT_EDIT_BANK: "update bank",
        TEXT_SAFE_NAME: "Safe Name",
        TEXT_SAFES: "Safes",
        TEXT_BANK_NAME_ARABIC: "bank name Arabic",
        TEXT_BANK_NAME_ENGLISH: "bank name English",
        TEXT_DEALERS: "Cust & Sup",
        TEXT_BALANCEL: "Balance",
        TEXT_ITEM_LIST: "List items",
        TEXT_ADD_TAX: "Add tax",
        TEXT_TAX_NAME: "Tax Name",
        TEXT_TAXES: "Taxes",
        TEXT_DATE: "Date",
        TEXT_FACTOR_POUND: "Factor to pound",
        TEXT_FACTOR_DOLAR: "Factor to dolar",
        TEXT_ACCOUNT_BALANCE: "Account balance",
        TEXT_FACTORY: "Factory",
        TEXT_CURRENCY_NAME: "Currency name",
        TEXT_CURRENCY_NAME_English: "Name In English",
        TEXT_SYMBOL: "Symbol",
        TEXT_DEFAULT: "Make It Default",
        TEXT_DEFAULTSpan: "Default",
        TEXT_ADD_CURRENCY: "Add currency",
        TEXT_CURRENCIES: "Currencies",
        TEXT_CLOSE: "Close",
        TEXT_ADD_COPMANY: "Add company",
        MSG_YOU_SHOULD_ADD_UNIT: "You should add one unit to this item",
        TEXT_NEXT: "Next",
        TEXT_MONEY_TRANSACTIONS: "Money transactions",
        TEXT_PAYMONEY: "Pay money",
        //permissions
        TEXT_SalesInvoicesReport: "Sale Invoices Report",
        TEXT_CustomersInvoicesWithFilterReport:
          "Customer Invoices With Filters ",
        TEXT_Backup: "Backup",
        TEXT_KsaInvoice: "Ksa Imvoice",
        TEXT_SalesInvoiceReport: "Sales Invoices Report",
        TEXT_InvoicesEarningsReport: "Invoices Earnings Report",
        TEXT_ProductsEarningsReport: "Products Earnings Report",
        TEXT_SupplierInvoicesReport: "Supplier Invoices Report",
        TEXT_MostActiveSuppliersReport: "Most Active Suppliers Report",
        TEXT_ProductsMovementsReport: "Products Movements Report",
        TEXT_ProductMovementReport: "Product Movement Report",
        TEXT_ProductsReport: "Products Report",
        TEXT_DemandLimitReport: "Products DemandLimit Report",
        TEXT_ProductExpirationReport: "Products Expiration Report",
        TEXT_StoreMovementReport: "Product Store Movements Report",
        TEXT_LedgerReport: "Ledger Report",
        TEXT_CustomerStatementReport: "Customer Statement Report",
        TEXT_CustomersReport: " Customers Report",
        TEXT_MostActiveCustomersReport: "Most Active Customers Report",
        TEXT_CustomerMovementAsInvoicesReport:
          "Customer Movemet As Invoices Report",
        TEXT_CustomerMovementAsPayMoneyReport:
          "Customer Movements As PayMoney Report",
        TEXT_SupplierStatemntReport: "Supplier Statemnt Report",
        TEXT_supplierReport: "Supplier Report",
        TEXT_SupplierMovementAsInvoicesReport:
          "Supplier Movement As Invoices Report",
        TEXT_SupplierMovementsAsPayMoney:
          "Supplier Movements As PayMoney Report ",
        TEXT_PAY_TO: "Pay to",
        TEXT_COLLECTMONEY: "Collect money",
        TEXT_AMOUNT: "amount",
        TEXT_INV_NUMBER: "Invoice Num",
        TEXT_TO_ACCOUNT: "To account",
        TEXT_FROM_ACCOUNT: "From account",
        TEXT_REQUIRED: "this field is required",
        TEXT_CREATE_SAFE: "add safe",
        TEXT_CREATE_BANK: "add bank",
        TEXT_SAFE_NAME: "Safe Name",
        TEXT_SAFES: "Safes",
        TEXT_BANK_NAME: "bank name",
        TEXT_BALANCEL: "Balance",
        TEXT_ITEM_LIST: "List items",
        TEXT_DASHBOARD: "Dashboard",
        TEXT_USERS: "Users",
        TEXT_LOGOUT: "Log out",
        TEXT_SIGNIN: "Sign in",
        TEXT_CREATE_USER: "Create user",
        TEXT_USER_CODE: "User code",
        TEXT_USER_NAME: "User name",
        TEXT_USER_CREATION_DATE: "User creation date",
        TEXT_FULL_NAME: "Full name",
        TEXT_PASSWORD: "Password",

        TEXT_USERNAME: "User name",
        TEXT_CONFIRM_PASSWORD: "Confirm password",
        TEXT_AGENT: "Agent",
        TEXT_EMPLOYEE: "Employee",
        TEXT_ADDRESS: "Address",
        TEXT_NATIONALITY: "Nationality",
        TEXT_ADD_USER: "Add user",
        TEXT_QUANTITY: "Quantity",
        TEXT_TOTALUNITPRICE: "Total unit Price",
        TEXT_TOTAL: "Total",

        TEXT_PLACEHOLDER_SEARCH: "Search ...",

        TEXT_EDIT: "Edit",
        TEXT_EDIT_PERMISSIONS: "Edit permissions",
        TEXT_REMOVE: "Remove",
        TEXT_ADD: "Add",
        TEXT_SELECTALL: "Select Or Delete All permissions",

        TEXT_CANCEL: "Cancel",
        TEXT_CREATE: "Create",
        TEXT_SAVE: "Save",
        TEXT_NEXT: "Next",
        TEXT_OPTIONS: "Options",

        TEXT_READ: "Read",
        TEXT_CREATE: "Create",
        TEXT_UPDATE: "Edit",
        TEXT_DELETE: "Delete",
        TEXT_PERMISSION: "Permission",

        TEXT_USERS_AND_PERMISSIONS: "Users and permissions",
        TEXT_GENERAL_LEDGER: "General ledger",
        TEXT_SALE_AND_PURCHASE: "Sale and purchase",
        TEXT_INVENTORY: "Inventory",
        TEXT_HR: "Human resources",

        //reset password
        TEXT_EMAIL_LOGIN: "Email",
        Text_update_password: "update password",
        Text_message:
          "Thanks for Confirm your Email let's update your password.",
        TEXT_EMAIL_REQUIRED: "Email required",
        TEXT_PASSWORD: "Password",
        TEXT_PASSWORD_REQUIRED: "Password required",
        TEXT_CONFIRM_PASSWORD: "Confirm password",
        MSG_INVALID_EMAIL: "invalid email",
        TEXT_RESET_PASSWORD: "Reset password",
        TEXT_MESSAGE_INSTRUCT:
          "If you forgot your password, well, then we’ll email you instructions to reset your password.",
        TEXT_RESET_LINK: "Send Reset Link",
        TEXT_RETURN_LOGIN: "Return to login",
        TEXT_ENTER_EMAIL: "Enter your email address",
        TEXT_CONFIRM_PASSWORD_REQUIRED: "confirm Password field is required. ",
        TEXT_PASS_CONFPASS_NOT_MATCH:
          "password and confirm password not match ",
        TEXT_ENTER_PASSWORD: "enter password",
        TEXT_CONFIRM_ENTER_PASSWORD: "enter confirm password",
        TEXT_LATER: "later",
        //change password
        TEXT_CURRENT_PASSWORD: "Current Password",
        TEXT_NEW_PASSWORD: "New Password",
        TEXT_CONFIRM_NEW_PASSWORD: "Confirm New Password",
        Text_CHANGE_password: "Change password",
        TEXT_CHANGE_TITLE_PASSWORD: "Change passowrd",
        TEXT_PASSWORD_CURRENT_REQUIRED: "current passowrd required",
        TEXT_PASSWORD_NEW_REQUIRED: "New Password required",
        TEXT_CONFIRM__NEW_PASSWORD_REQUIRED: "confirm new passowrd required",
        /* permissions */

        TEXT_Role: "Roles",
        TEXT_Users: "Users",
        TEXT_product: "Products",
        TEXT_Category: "Category",
        TEXT_Store: "Store",
        TEXT_Currency: "Currency",
        TEXT_Report: "Reports",
        TEXT_Inventory: "inventory",
        TEXT_SupplierInvoice: "supplier Invoice",
        TEXT_CustomerInvoice: "customer Invoice",
        TEXT_Accountant: "Accountant",
        TEXT_Customer: "Customers",
        TEXT_Supplier: "Suppliers",
        TEXT_Branch: "branches",
        TEXT_Company: "company",
        TEXT_Bank: "bank",
        TEXT_Transaction: "transactions",
        TEXT_PayMoney: "payMoney",
        TEXT_CHART_OF_ACCOUNT: "Chart of account",
        TEXT_COST_CENTERS: "Cost centers",
        TEXT_ASSETS: "Assets",
        TEXT_SUPLIERS: "Suppliers",
        TEXT_CUSTOMERS: "Customers",
        TEXT_BANKS: "Banks",
        TEXT_CASES: "Cases",
        TEXT_TRANSACTIONS: "Transactions",
        TEXT_ACCOUNT_TYPE: "Account Type",
        TEXT_BANKACCOUNTNUMBER: "Bank Account Number",
        TEXT_INVOICES: "Invoices",
        TEXT_RETURNS: "Returns",
        TEXT_FREE_RETURNS: "Free return",
        TEXT_BRANSHES: "Branshes",
        TEXT_COMISSIONS: "Comissions",
        TEXT_DISCOUNTS: "Discounts",

        TEXT_WAREHOUSE: "Warehouse",
        TEXT_ITEMS: "Items",
        TEXT_BARCODES: "Barcodes",
        TEXT_UNITES: "Unites",

        TEXT_EMPLOYEE_FILES: "Employee files",
        TEXT_PAYROLL: "payroll",
        TEXT_PAYSLIP: "payslip",
        TEXT_BENEFITS: "benefits",
        TEXT_DEDUCTIONS: "deductions",
        TEXT_HOLIDAYS: "Holidays",

        TEXT_ITEMS: "Items",
        TEXT_ITEM_CODE: "Item code",
        TEXT_ITEM_NAME: "Item name",
        TEXT_ITEM_CREATION_DATE: "Item creation date",
        TEXT_CREATE_ITEM: "Create item",

        TEXT_CREATE_ITEM: "Create item",
        TEXT_ITEM_NAME: "Item name",
        TEXT_ITEM_DESCRIPTION: "Item Description",
        TEXT_CHOOSE_CATEGORIES: "Choose categories of item",

        // Messages
        MSG_NO_RESULT: "There's No Results Now",
        MSG_REQUIRED: "Required *  please fill this field first",
        MSG_UNMATCHED: "Password is not matched",
        MSG_WENT_WRONG: "Something went wrong !",
        MSG_Login_Failed: "Username or password wrong :/",
        MSG_DUPLICATE_NAME: "This username is already taken",
        MSG_LOGIN_SUCCESS: "login successfully",
        MSG_ADDEDSUCCESSFULLY: "add successfully",
        MSG_DELETED_SUCCESSFULLY: "Deleted successfully",
        MSG_UPDATEDSUCCESSFULLY: "updated successfully",
        MSG_COMPANYNAMEEXIST: "company Name may be exist",
        MSG_BRANCHNAMEEXIST: "branch Name may be exist",
        MSG_NOACCESS: "Dot not have access",
        MSg_USEREXIST: "user or email may be exist",
        MSG_DEFAULTCURRENCYEXIST: "there exist default currency already",
        MSG_TAXEXIST: "Tax already exist",
        MSG_STORE_EXIST: "Store may be exist",
        MSG_CATEGORY_EXIST: "Category may be exist",
        MSG_UNIT_EXIST: "unit may be exist",
        MSG_OLD_PASSWORD_INCORRECT: "old password not correct",
        MSG_another_user_already_loged: "another user already loged",
        MSG_PRODUCT_EXIST: "product may be exist",
        MSG_STORE_NOT_EXIST: "store not exist",
        MSG_CATEGORY_NOT_EXIST: "category notb exist",
        MSG_PRODUCT_CODE_EXIST: "product code may be exist",
        // settings
        TEXT_SETTINGS: "Settings",
        ADD: "Add",
        TEXT_BACK: "back",
        CANCEL: "Cancel",
        CHOOSE: "Choose",
        UPDATE: "Update",
        CONFIRM: "Confirm",
        CONFIRMMESSAGE: "Are You Sure",
        MSG_DEFAULTCURRENCYADDED: "Default currency Added successfully",
        TEXT_CHOOSEDEFAULTCURRENCY: "Choose Default Currency",
        //adduser

        TEXT_CREATE_USER: "Add User",
        TEXT_EDITUSER: "Edit User",
        TEXT_USERS: "Users",
        USERNAME: "User Name",
        ROLE: "Role",
        STATE: "IsActive",
        Password: "Password",
        ISNOTACTIVE: "Not Active",
        ISACTIVE: "Active",
        TEXT_ROLE_REQUIRED: "Role Name required",
        TEXT_EMAIL_REQUIRED: "Email required",
        TEXT_PASSWORD_REQUIRED: "Password required",
        MSG_ROLE_EXIST: "Role already exist",
        MSG_INVALID_EMAIL: "invalid email",
        //logs
        TEXT_LOGS: "Logs",
        Text_ACTION_LOG: "Action",
        Text_USER_LOG: "userResponsable",
        Text_DESCRIPTION_LOG: "description",
        TEXT_DATE_LOG: "Date of Action",
        //Text_addcompany

        Text_addcompany: "Add Company",
        Text_companyName: "Company Name",
        Text_companyactivity: "Company Activity",
        Text_companyRegNo: "REgistration No",
        Text_companyTaxcard: "Tax Card",
        Text_companyAddress: "Address",
        Text_phone: "Phone",
        Text_mobilephone: "Mobile Phone",
        Text_Email: "Email",
        Text_website: "Website",
        Text_logo: "Logo",
        Text_curreny: "Currency",
        TEXT_COUNTRY: "Country",
        Text_branchName: "Branch Name",
        TEXT_BRANCHREQUIRED: "branch name required",
        Text_addbranch: "Add Branch",
        TEXT_EDITCOMPANYINFO: "Edit Company Information",
        TEXT_BRANCHLIST: "Branch List",
        TEXT_COMPANYSETTING: "Company Setting",
        TEXT_BRANCHSETTING: "Branches Setting",
        Text_COMPANYINFO: "Company Information",
        TEXT_UPDATETAX: "update tax",
        TEXT_UPDATECURRENCY: "update currency",

        //role
        Text_Roles: "Roles",
        Text_AddRole: "AddRole",
        Text_RoleName: "Role Name",
        Text_RoleRequired: "role name is required",
        Text_deleteRole: "delete role",
        Text_ManagePermission: "manage permissions",
        Text_AddAndDeletePermission: " Add/Remove Permissions",
        Text_Module: "Module",
        Text_ConfirmdeleteRole: "Are you sure delete role ?",
        //customers
        TEXT_CUSTOMERS: "Customers",
        TEXT_EXIST: "You have total",
        TEXT_Customer: "customers",
        TEXT_CustomerName: "Customer Name",
        Text_Balance: "Balance",
        Text_Address: "Address",
        TEXT_customerRequired: "customer Name required",
        TEXT_AddressRequired: "address is required.",
        TEXT_PhoneRequired: "phone is required",
        TEXT_FAX: "Fax",
        TEXT_DISCOUNT: "Discount",
        TEXT_HomeMobile: "Home Mobile",
        TEXT_DEBIT: "Debit",
        TEXT_CREDIT: "Credit",
        TEXT_CUSTOMERANDSUPPLIER: "customerAndSupplier",
        TEXT_ADDCUSTOMER: "Add Customer",
        TEXT_UPDATECUSTOMER: "update customer",
        TEXT_SPEND_PRICE: "Spend Price",

        //suppliers
        TEXT_SUPPLIERS: "Suppliers",
        TEXT_EXIST: "You have total",
        TEXT_Supplier: "suppliers",
        TEXT_SupplierName: "Supplier Name",
        Text_Balance: "Balance",
        Text_Address: "Address",
        TEXT_supplierRequired: "supplier Name required",
        TEXT_AddressRequired: "address is required.",
        TEXT_PhoneRequired: "phone is required",
        TEXT_FAX: "Fax",
        TEXT_DISCOUNT: "Discount",
        TEXT_HomeMobile: "Home Mobile",
        TEXT_DEBIT: "Debit",
        TEXT_CREDIT: "Credit",
        TEXT_SUPPLIERANDCUSTOMER: "supplierAndCupplier",
        TEXT_ADDSUPPLIER: "Add Supplier",
        TEXT_UPDATESUPPLIER: "update supplier",

        //dashboard
        DASHBOARD: "Dashboard",
        //role
        Text_Roles: "Roles",
        Text_AddRole: "AddRole",
        Text_RoleName: "Role Name",
        Text_RoleRequired: "role name is required",
        Text_deleteRole: "delete role",
        Text_ManagePermission: "manage permissions",
        Text_AddAndDeletePermission: " Add/Remove Permissions",
        Text_Module: "Module",
        Text_ConfirmdeleteRole: "Are you sure delete role ?",

        // customer Invoice
        TEXT_ADDCUSTOMERINVOICE: "Add Customer Invoice",
        TEXT_INVOICENUMBER: "Invoice number",
        TEXT_DESCRIPTION: "Description",
        TEXT_CUSTOMERINVOICEDATE: "Invoice Date",
        TEXT_PAYMENTTYPE: "Payment Type",
        MSG_ADDPAYMENTTYPE: "Add Payment Type",
        TEXT_PAYMENTNAME: "Payment Name",
        TEXT_INVOICEMADEBY: "MadeBy",
        TEXT_PAYMENTEXIST: "Payment already Exist",
        TEXT_INVOICEDETAILS: "Invoice Details",
        TEXT_QUANTITY: "Quantity",
        TEXT_UNIT: "Unit",
        TEXT_TOTALUNITPRICE: "total unit price",
        TEXT_TAX: "Tax",
        TEXT_TOTAL: "Total Price",
        TEXT_CURRENCY: "Currency",
        TEXT_ADDNEW: "Add New",
        TEXT_CUSTOMERINVOICE: "Selling Invoices",
        TEXT_PAIED: "Paied",
        AVAILABLE_STOCK: "Available Stock",

        //bank accounts
        TEXT_BANKACCOUNTS: "Bank Accounts",
        TEXT_BANK_ACCOUNTS: "Bank Account",
        TEXT_ACCOUNT_TYPE: "BankAccountType",
        TEXT_BANKACCOUNTNUMBER: "BankAccountNumber",
        TEXT_BANKACCOUNTNAME: "BankAccountName",
        TEXT_BANKACCOUNTNAMEREQUIRED: "bank account name required",
        TEXT_BANKACCOUNTNUMBERREQUIRED: "bank account number required",
        TEXT_BANKREQUIRD: "bank required",
        TEXT_UPDATEBANKACCOUNT: "update bank account",
        TEXT_FACTOR: "ExchangeRateForDefaultCurrency",

        //invoice

        TEXT_INVOICES: "Invoices",
        TEXT_SUPLIERSINVOICE: "Supplier Invoice",
        TEXT_ADDSUPPLIERINVOICE: "Add Supplier Invoice",
        Text_ADDINVOICE: "Add Invoice",
        // customer Invoice
        TEXT_CUSTOMER_INVOICE: "فواتير البيع",
        TEXT_ADDCUSTOMERINVOICE: "Add Customer Invoice",
        TEXT_INVOICENUMBER: "Invoice number",
        TEXT_DESCRIPTION: "Description",
        TEXT_CUSTOMERINVOICEDATE: "Invoice Date",
        TEXT_PAYMENTTYPE: "Payment Type",
        MSG_ADDPAYMENTTYPE: "Add Payment Type",
        TEXT_PAYMENTNAME: "Payment Name",
        TEXT_PAYMENTEXIST: "Payment already Exist",
        TEXT_INVOICEDETAILS: "Invoice Details",
        TEXT_QUANTITY: "Quantity",
        TEXT_UNIT: "Unit",
        TEXT_TOTALUNITPRICE: "total unit price",
        TEXT_TAX: "Tax",
        TEXT_TOTAL: "Total Price",
        TEXT_CURRENCY: "Currency",
        TEXT_ADDNEW: "Add New",
        //bank accounts
        TEXT_BANKACCOUNTS: "Bank Accounts",
        TEXT_BANK_ACCOUNTS: "Bank Account",
        TEXT_ACCOUNT_TYPE: "BankAccountType",
        TEXT_BANKACCOUNTNUMBER: "BankAccountNumber",
        TEXT_BANKACCOUNTNAME: "BankAccountName",
        TEXT_BANKACCOUNTNAMEREQUIRED: "bank account name required",
        TEXT_BANKACCOUNTNUMBERREQUIRED: "bank account number required",
        TEXT_BANKREQUIRD: "bank required",

        //ui-select placeholders
        TEXT_CHOOSEROLE: "choose role",
        TEXT_CHOOSEBANK: "choose bank",
        TEXT_CHOOSEBANKACCOUNTTYPE: "choose bank account type",
        TEXT_CHOOSEACCOUNT: "choose account",
        TEXT_CHOOSECURRENCY: "choose currency",
        TEXT_CHOOSESUPPLIER: "chhose supplier",
        TEXT_CHOOSECUSTOMER: "choose customer",
        TEXT_CHOOSEPATTYPE: "choose pay type",
        TEXT_CHOOSEBRANCH: "choose branch",

        //PRODUCT
        TEXT_ADDPRODUCT: "Add Item",
        maininformation: "Main Informations",
        TEXT_PRODUCTCODE: "Item Code",
        TEXT_PRODUCTNAME: "Item Name",
        category: "Category",
        store: "Store",
        TEXT_CATEGORY: "Category",
        addProduct: "Add Item ",
        store: "Store",
        demandLimit: "Demand Limit",
        addStore: "Add Store",
        addCategory: "Add Category",
        storeRequired: "Store Required",
        description: "Description",
        descriptionRequired: "Description Required",
        categoryName: "Category Name",
        storeName: "Store Name",
        code: "Code",
        codeRequired: "Code Required",
        productName: "Item Name",
        nameRequired: "Name Required",
        productBarCode: "BarCode",
        units: "Units",
        barCodeRequired: "Barcode Required",
        price: "Price",
        priceRequired: "Price Required",
        categoryadd: "Add Category",
        categoryRequired: "Category Required",
        sellerPrice: "Sell Price",
        sellerPriceAmount: "Profit margin Amount",
        sellerPricePercent: "Profit margin Percent",
        sellerPriceRequired: "Sell Price Required",
        purchesePrice: "Purchasing Price",
        purchesePriceRequired: "Purchasing Price Required",
        tax: "Tax",
        taxRequired: "Tax Required",
        stock: "Stock",
        stockRequired: "Stock Required",
        orderLimit: "Demand Limit",
        orderLimitRequired: "Demand Limit Required",
        unitName: "Unit Name",
        unitNameRequired: "Unit Name Required",
        sellingprice: "Sell Price",
        purchasingPric: "Purchasing Price",
        defaultSelling: "Default Selling",
        defaultPurchasing: "Default Purchasing",
        unitPriceRequired: "Unit Price Required",
        isExpiration: "IsExpiration",
        Expiration: "Expiration",
        productionDate: "Production Date",
        productionDateRequired: "Production Date Required",
        expirationDate: "Expiration Date",
        expirationDateRequired: "Expiration Date Required",
        width: "Width",
        widthRequired: "Width Required",
        height: "Hieght",
        heightRequired: "Hieght Required",
        elevation: "Elevation",
        elevationRequired: "Elivation Required",
        TEXT_ADD_TRANSACTION: "Add Transaction",
        size: "Size",
        sizeRequired: "الحجم مطلوب",
        weight: "الوزن القائم",
        weightRequired: "مطلوب",
        netWeight: "الوزن الصافي",
        netWeightRequired: "مطلوب",
        selectStore: "Select Store",
        selectCategory: "Select Category",
        units: "Units",
        dimensions: "Dimentions",
        add: "Add",
        AddNewUnit: "Add New Unit",
        currentBalance: "Current Balance",
        startbakance: "Opening Balance",
        balanceUnit: "Unit For Openning Balance",
        balanceCost: "Balance Cost",
        completAccount: "الحساب المكمل",
        choseUnit: "---Choose Unit---",
        choseAccount: "---- Choose Account----",
        defaultSell: "Default Selling",
        defaultPerchase: "Default Purchasing",
        storeaccount: "المخزون",
        storeaccount: "رصيد المخزون",
        editproduct: "Edit Item",
        storeaccountbalance: "حساب المخزون",
        TEXT_QUANTITY: "Quantity",
        TEXT_TOTALUNITPRICE: "Total Unit Price",
        TEXT_TOTAL: "Total",
        //store relocations
        TEXT_STORE_RELOCATION: "store relocations",
        TEXT_ADD_PRODUCT_RELOCATE: "Add Product",
        TEXT_ADD_STORE_RELOCATE: "Add Store Relocate",
        TEXT_STORE_FROM: "From Store",
        TEXT_STORE_TO: "To Store",
        MSG_RELOCATE_SUCCESSFULLY: "relocated successfully",
        TEXT_DESCRIPTION: "Description",
        TEXT_PRODUCT_RELOCATE: "Product Name",
        TEXT_QUANTITY_RELOCATE: "QuantityToBeRelocate",
        TEXT_AMOUNT_RELOCATE: "Residual",
        TEXT_STOCK_RELOCATE: "Stock",

        //categories
        TEXT_CATEGORIES: "Categories",
        TEXT_CATEGORY_NAME: "Category Name",
        Text_Category_REQUIRED: "category required",
        TEXT_UPDATE_CATEGORY: "update Category",

        // manage stores
        TEXT_STORES: "Stores",
        TEXT_STORE_NAME: "Store Name",
        Text_Category_REQUIRED: "store name required",
        TEXT_UPDATE_STORE: "update store",

        //manage units
        TEXT_UNITS: "Units",
        TEXT_UNIT_NAME: "Unit Name",
        Text_UNIT_REQUIRED: "Unit name required",
        TEXT_UPDATE_UNIT: "Update Unit",
        TEXT_ADD_UNIT: "Add Unit",
        TEXT_INTERVAL: "Interval For Deleting Logs",
        TEXT_Daily: "Daily",
        TEXT_Weekly: "Weekly",
        TEXT_Monthly: "Monthly",
        TEXT_Yearly: "Yearly",
        TEXT_BACKUP: "Backups",
        TEXT_BACKUP_DB: "Backups for Database ",
        TEXT_TAKE_BACKUP: "Take Backup",
        MSG_BACKUP_SUCCESS: "Backups Successfully",
        TEXT_BACUP_FILE: "FileName",
        TEXT_CREATION_AT: "Time",
        TEXT_RESTORE: "RestoreDataBase",
        MSG_RESTORE_SUCCESS: "Restore Database successfully",
        TEXT_COST: "CostCenter",
      },
    };
  },
]);
